version: '3.8'
services:
  db:
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: mysqladmin ping --silent
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
  api:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    networks:
      - app_network
volumes:
  mysql:
networks:
  app_network: